# Generated by Django 3.1.6 on 2023-07-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('sexo', models.CharField(max_length=200, null=True)),
                ('data_nascimento', models.DateField(null=True)),
            ],
            options={
                'db_table': 'pessoas',
            },
        ),
    ]
